# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df238fa13f56f668b2795ff854e4cc7b5e024e63e0edca20626c3d0e494c53e7228fb54d729b5faaf7506d3f3f0d112350fe40bee0ba38dd4c3a6ffe5789e75b
  yammer_api_key: 4KREZBo8OcxaiVHohzRQ2Q
  yammer_api_secret: 0eUgYeZhCkdqbruloJTuiSVLoOiPlc9mgymCUdKbBKo

test:
  secret_key_base: b41ef7da2dcdcd4e22e723d722651cbbc7d620c6e6649ca55eea92f1a8a1279c57aacf6630f8f206b4c96dca0d7741bf6b0446be321e127dbf8b6144cdb06440
  yammer_api_key: 4KREZBo8OcxaiVHohzRQ2Q
  yammer_api_secret: 0eUgYeZhCkdqbruloJTuiSVLoOiPlc9mgymCUdKbBKo

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yammer_api_key: <%= ENV['yammer_api_key'] %>
  yammer_api_secret: <%= ENV['yammer_api_secret'] %>
  database: <%= ENV['database'] %>
  database_user: <%= ENV['database_user'] %>
